/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const TRANSLATIONS = {
  title: "마법 성의 토끼",
  subtitle: "마법 계단을 올라 성 꼭대기에 도달하세요!",
  floor: "층",
  magicLevel: "마법 레벨",
  gems: "보석",
  current: "현재",
  controls: "조작 방법",
  move: "이동",
  jump: "점프",
  objective: "목표",
  objectiveDesc: "마법사 토끼가 마법 성의 꼭대기에 도달하도록 도와주세요!",
  magicStatus: "마법 상태",
  manaCharging: "마력 충전 중",
  magicPower: "마법 위력",
  magicLock: "마법 자물쇠!",
  solveToOpen: "문을 열기 위해 문제를 푸세요:",
  unlock: "잠금 해제",
  success: "성공!",
  doorOpens: "마법의 문이 열립니다...",
  reward: "보상",
  congratulations: "축하합니다!",
  winDesc: "마법 성의 꼭대기에 도달했습니다!",
  playAgain: "다시 하기",
  start: "시작",
  goal: "목표",
  shop: "상점",
  shopWelcome: "마법 상점에 오신 것을 환영합니다!",
  buy: "구매",
  equipped: "장착됨",
  notEnoughGems: "보석이 부족합니다!",
  close: "닫기",
  accessoryWizardHat: "마법사 모자",
  accessoryCrown: "황금 왕관",
  accessoryTopHat: "신사 모자",
  accessoryRedCape: "빨간 망토",
  accessoryBlueCape: "파란 망토",
  accessoryGoldCape: "황금 망토",
};
